apiVersion: v1
kind: ConfigMap

metadata:
  name: homepage-config
  namespace: homepage

data:
  bookmarks.yaml: |
    - Communities:
        - Reddit:
            - href: https://reddit.com/
            - icon: reddit.png

        - Discord:
            - href: https://discord.gg/homelab
            - icon: discord.png
    - Developer:
        - GitHub:
            - href: https://github.com

        - Kubernetes Docs:
            - href: https://kubernetes.io/docs/

        - cert-manager Docs:
            - href: https://cert-manager.io/docs/

    - Security:
        - CVE Details:
            - href: https://www.cvedetails.com/

        - VirusTotal:
            - href: https://virustotal.com/

  services.yaml: |
    - Self Hosted:
        - Home Assistant:
            href: https://ha.quantumsec.in
            icon: home-assistant.png

        - Pi-hole:
            href: https://pihole.quantumsec.in
            icon: pi-hole.png

        - Vaultwarden:
            href: https://thevault.gslb.quantumsec.in
            icon: vaultwarden.png

        - TrueNAS:
            href: https://truenas.quantumsec.in
            icon: truenas.png

        - Grafana:
            href: https://grafana.gslb.quantumsec.in
            icon: grafana.png

        - Immich:
            href: https://photos.quantumsec.in
            icon: immich.png

        - AdGuard DNS:
            href: http://dns-01.quantumsec.in
            icon: adguard-home.png

        - Authentik:
            href: https://auth.gslb.quantumsec.in
            icon: authentik.png

    - Infrastructure:
        - OPNsense:
            href: https://10.10.10.1
            icon: opnsense.png

        - PVE-01:
            href: https://pve-01.quantumsec.in:8006
            icon: proxmox.png

        - PVE-02:
            href: https://pve-02.quantumsec.in:8006
            icon: proxmox.png

        - TL-SG108E:
            href: http://10.10.10.20
            icon: tp-link.png

        - Jio Gateway:
            href: http://192.168.29.1
            icon: router.png
        
        - Windows Server:
            href: rdp://10.10.10.32
            icon: microsoft-windows.png

    - Kubernetes:
        - Homepage:
            href: https://home.quantumsec.in
            icon: homepage.png

        - Whoami:
            href: https://whoami.quantumsec.in
            icon: traefik.png

        - cert-manager:
            href: https://cert.quantumsec.in
            icon: cert-manager.png
        - ArgoCD:
            href: https://argocd.quantumsec.in
            icon: argo-cd.png
  settings.yaml: |
    title: QuantumSec Platform

    theme: dark
    color: slate

    headerStyle: clean

    layout:
      Self Hosted:
        style: row
        columns: 4

      Infrastructure:
        style: row
        columns: 4

      Kubernetes:
        style: row
        columns: 4

  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

    - search:
        provider: google
        target: _blank
