- Self Hosted:
    - Home Assistant:
        href: https://ha.quantumsec.in
        icon: home-assistant.png

    - Pi-hole:
        href: https://pihole.quantumsec.in
        icon: pi-hole.png

    - Vaultwarden:
        href: https://thevault.gslb.quantumsec.in
        icon: vaultwarden.png

    - TrueNAS:
        href: https://truenas.quantumsec.in
        icon: truenas.png

    - Grafana:
        href: https://grafana.gslb.quantumsec.in
        icon: grafana.png

    - Immich:
        href: https://photos.quantumsec.in
        icon: immich.png

    - AdGuard DNS:
        href: https://dns-01.quantumsec.in
        icon: adguard-home.png

    - Authentik:
        href: https://auth.gslb.quantumsec.in
        icon: authentik.png

- Infrastructure:
    - OPNsense:
        href: https://10.10.10.1
        icon: opnsense.png

    - PVE-01:
        href: https://pve-01.quantumsec.in
        icon: proxmox.png

    - PVE-02:
        href: https://pve-02.quantumsec.in
        icon: proxmox.png

    - TL-SG108E:
        href: http://10.10.10.x
        icon: tp-link.png

    - Jio Gateway:
        href: http://192.168.29.1
        icon: router.png
    - Windows Server:
        href: https://10.10.10.32
        icon: windows-server.png

- Kubernetes:
    - Homepage:
        href: https://home.quantumsec.in
        icon: homepage.png

    - Whoami:
        href: https://whoami.quantumsec.in
        icon: traefik.png

    - cert-manager:
        href: https://cert.quantumsec.in
        icon: cert-manager.png
